theme: jekyll-theme-minimal
title: 魏县第五小学
description: 魏县第五小学始建于2017年，坐落在龙乡南大街西侧，占地面积23500平方米，建筑面积12000平方米。学校现有教学班48个，在校生2400人；学校现有教职工158人，其中省、市级骨干教师13人，高级教师15人，县级以上名师18人。学历达标率100%，普通话达标率100%，继续教育参训率100%。
